/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class DemoRequestActivitySchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'demoRequestId', 'id', 'userId'] as const
  $columns = DemoRequestActivitySchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demoRequestId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
}

export class DemoRequestSchema extends BaseModel {
  static $columns = ['activeMembers', 'businessType', 'closedAt', 'company', 'contactedAt', 'conversionPage', 'convertedAt', 'createdAt', 'demoScheduledAt', 'email', 'fullName', 'id', 'ipHash', 'landingPage', 'marketingSessionId', 'marketingVisitorId', 'message', 'phone', 'qualifiedAt', 'referrer', 'updatedAt', 'userAgent', 'utmCampaign', 'utmContent', 'utmMedium', 'utmSource', 'utmTerm'] as const
  $columns = DemoRequestSchema.$columns
  @column()
  declare activeMembers: string | null
  @column()
  declare businessType: string | null
  @column.dateTime()
  declare closedAt: DateTime | null
  @column()
  declare company: string
  @column.dateTime()
  declare contactedAt: DateTime | null
  @column()
  declare conversionPage: string | null
  @column.dateTime()
  declare convertedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare demoScheduledAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ipHash: string | null
  @column()
  declare landingPage: string | null
  @column()
  declare marketingSessionId: number | null
  @column()
  declare marketingVisitorId: number | null
  @column()
  declare message: string | null
  @column()
  declare phone: string | null
  @column.dateTime()
  declare qualifiedAt: DateTime | null
  @column()
  declare referrer: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userAgent: string | null
  @column()
  declare utmCampaign: string | null
  @column()
  declare utmContent: string | null
  @column()
  declare utmMedium: string | null
  @column()
  declare utmSource: string | null
  @column()
  declare utmTerm: string | null
}

export class MarketingEventSchema extends BaseModel {
  static $columns = ['id', 'locale', 'occurredAt', 'page', 'section', 'sessionId', 'theme', 'visitorId'] as const
  $columns = MarketingEventSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string | null
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare page: string | null
  @column()
  declare section: string | null
  @column()
  declare sessionId: number | null
  @column()
  declare theme: string | null
  @column()
  declare visitorId: number
}

export class MarketingSessionSchema extends BaseModel {
  static $columns = ['deviceCategory', 'id', 'landingPage', 'lastActivityAt', 'locale', 'referrer', 'referrerHost', 'sessionUuid', 'startedAt', 'utmCampaign', 'utmContent', 'utmMedium', 'utmSource', 'utmTerm', 'visitorId'] as const
  $columns = MarketingSessionSchema.$columns
  @column()
  declare deviceCategory: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare landingPage: string | null
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column()
  declare locale: string | null
  @column()
  declare referrer: string | null
  @column()
  declare referrerHost: string | null
  @column()
  declare sessionUuid: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare utmCampaign: string | null
  @column()
  declare utmContent: string | null
  @column()
  declare utmMedium: string | null
  @column()
  declare utmSource: string | null
  @column()
  declare utmTerm: string | null
  @column()
  declare visitorId: number
}

export class MarketingVisitorSchema extends BaseModel {
  static $columns = ['createdAt', 'firstLandingPage', 'firstLocale', 'firstReferrer', 'firstReferrerHost', 'firstSeenAt', 'firstUtmCampaign', 'firstUtmMedium', 'firstUtmSource', 'id', 'lastSeenAt', 'updatedAt', 'visitorUuid'] as const
  $columns = MarketingVisitorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare firstLandingPage: string | null
  @column()
  declare firstLocale: string | null
  @column()
  declare firstReferrer: string | null
  @column()
  declare firstReferrerHost: string | null
  @column.dateTime()
  declare firstSeenAt: DateTime
  @column()
  declare firstUtmCampaign: string | null
  @column()
  declare firstUtmMedium: string | null
  @column()
  declare firstUtmSource: string | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastSeenAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitorUuid: string
}

export class MarketingWhatsappIntentSchema extends BaseModel {
  static $columns = ['clickedAt', 'contactedAt', 'contactedBy', 'createdAt', 'demoRequestId', 'eventId', 'expiresAt', 'id', 'linkedAt', 'linkedBy', 'locale', 'page', 'reference', 'section', 'sessionId', 'updatedAt', 'visitorId'] as const
  $columns = MarketingWhatsappIntentSchema.$columns
  @column.dateTime()
  declare clickedAt: DateTime
  @column.dateTime()
  declare contactedAt: DateTime | null
  @column()
  declare contactedBy: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare demoRequestId: number | null
  @column()
  declare eventId: bigint | number | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare linkedAt: DateTime | null
  @column()
  declare linkedBy: number | null
  @column()
  declare locale: string | null
  @column()
  declare page: string | null
  @column()
  declare reference: string
  @column()
  declare section: string | null
  @column()
  declare sessionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitorId: number | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
