/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/accounts.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/business.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/leads.ts" />
/// <reference path="../../config/limiter.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/mail.ts" />
/// <reference path="../../config/marketing_tracking.ts" />
/// <reference path="../../config/marketing.ts" />
/// <reference path="../../config/roles.ts" />
/// <reference path="../../config/seo.ts" />
